/* Curated defense/space capital + accelerator directories.
   These are research starting points compiled from public sources (fund sites,
   OpenVC's defense-tech list, MIT MIX) — check sizes and stages shift; always
   verify on the investor's own site before outreach. */

export const VENTURE_SOURCES = [
  { label: "OpenVC — defense-tech investor list", href: "https://www.openvc.app/investor-lists/defensetech-investors" },
  { label: "OpenVC — aerospace investor list", href: "https://www.openvc.app/investor-lists/aerospace-investors" },
  { label: "VC Sheet — investor profiles", href: "https://www.vcsheet.com/investors" },
  { label: "MIT MIX — defense startup resources", href: "https://mix.mit.edu/defense-technology-startup-resources/" },
  { label: "Pillar VC — how to build an investor list", href: "https://www.pillar.vc/playlist/article/how-to-build-an-investor-list/" },
];

/* Paid / account-gated research tools — no free data, but worth knowing. */
export const RESEARCH_TOOLS = [
  { label: "PitchBook", href: "https://pitchbook.com", note: "The deepest paid investor database — fund mandates, dry powder, contacts" },
  { label: "Carta", href: "https://carta.com", note: "Cap-table platform; useful once a round is actually closing" },
  { label: "InvestorLists.vc", href: "https://investorlists.vc", note: "Paid contact lists of active US VCs" },
];

const RAW_INVESTORS = [
  { name: "Founders Fund", checkSize: "$1M–$100M+", stage: "Seed–Growth", sectors: "Defense, Space, Deep tech", techAreas: "Launch, autonomy, AI, manufacturing", checkType: "Priced equity", traction: "Contrarian conviction; exceptional founders over metrics", url: "https://foundersfund.com", notes: "Anduril/SpaceX/Palantir backer; comfortable with long defense sales cycles" },
  { name: "Andreessen Horowitz (American Dynamism)", checkSize: "$1M–$50M", stage: "Seed–Series C", sectors: "Defense, Aerospace, Industrial", techAreas: "Autonomy, AI, manufacturing, space", checkType: "Priced equity", traction: "Strong team + mission pull; gov traction accelerates", url: "https://a16z.com/american-dynamism/", notes: "Dedicated American Dynamism practice; also runs a16z speedrun accelerator" },
  { name: "Shield Capital", checkSize: "$1M–$10M", stage: "Seed–Series A", sectors: "National security, Dual-use", techAreas: "AI, autonomy, cyber, space", techType: "", checkType: "Priced equity", traction: "Dual-use thesis; early gov signal (SBIR/OTAs) valued", url: "https://shieldcap.com", notes: "Operator GPs with DoD backgrounds" },
  { name: "Lux Capital", checkSize: "$2M–$50M", stage: "Seed–Growth", sectors: "Deep tech, Defense, Space", techAreas: "Semiconductors, robotics, bio, space", checkType: "Priced equity", traction: "Hard-science differentiation; IP moat", url: "https://luxcapital.com", notes: "Anduril, Hadrian, Varda portfolio" },
  { name: "Khosla Ventures", checkSize: "$1M–$50M", stage: "Seed–Growth", sectors: "Deep tech, Space, Energy", techAreas: "Propulsion, AI, materials, climate", checkType: "Priced or SAFE", traction: "Bold technical bets; prototype-stage OK", url: "https://khoslaventures.com", notes: "High risk tolerance for physics-hard problems" },
  { name: "Sequoia Capital", checkSize: "$1M–$100M", stage: "Seed–Growth", sectors: "Broad incl. Defense/AI", techAreas: "AI/ML, infrastructure, security", checkType: "Priced equity", traction: "Category-defining potential; strong revenue signal at A+", url: "https://sequoiacap.com", notes: "Selective in defense; AI-first thesis" },
  { name: "General Catalyst", checkSize: "$2M–$100M", stage: "Seed–Growth", sectors: "Defense & Intelligence, Resilience", techAreas: "AI, space, cyber, industrial", checkType: "Priced equity", traction: "Mission + commercial dual-path", url: "https://generalcatalyst.com", notes: "Dedicated global resilience practice (Anduril, Helsing)" },
  { name: "8VC", checkSize: "$1M–$30M", stage: "Seed–Series B", sectors: "Defense, Logistics, Bio", techAreas: "Data infrastructure, autonomy, manufacturing", checkType: "Priced equity", traction: "Systems-level theses; founder-market fit", url: "https://8vc.com", notes: "Palantir lineage; strong DC network" },
  { name: "In-Q-Tel (IQT)", checkSize: "$500K–$3M typical", stage: "Series A–C (product-ready)", sectors: "Intelligence & National security", techAreas: "AI, cyber, space, biotech, comms", checkType: "Equity + work program", traction: "Deployable product an IC customer needs", url: "https://iqt.org", notes: "Strategic investor for the intelligence community; brings mission customers" },
  { name: "National Security Innovation Capital (NSIC)", checkSize: "$1M–$3M", stage: "Pre-seed–Series A", sectors: "Dual-use hardware", techAreas: "Autonomy, power, space, comms, sensors", checkType: "Non-dilutive-style agreements (OT)", traction: "Hardware prototype needing acceleration; US ownership", url: "https://www.diu.mil/nsic", notes: "DoD program (under DIU) funding hardware startups that lack trusted capital" },
  { name: "Defense Innovation Unit (DIU)", checkSize: "Contracts (not equity)", stage: "Any (commercial product)", sectors: "All DoD mission areas", techAreas: "AI, autonomy, space, cyber, energy, human systems", checkType: "OT prototype → production contracts", traction: "Fieldable commercial technology", url: "https://www.diu.mil", notes: "Not an investor — the fastest commercial-to-DoD contracting front door; pairs well with venture backing" },
  { name: "Draper Associates", checkSize: "$250K–$5M", stage: "Pre-seed–Series A", sectors: "Deep tech, Space, Crypto", techAreas: "Space, AI, frontier tech", checkType: "SAFE or priced", traction: "Visionary founder; early product", url: "https://draper.vc", notes: "Tim Draper's early-stage fund (SpaceX early backer)" },
  { name: "Space Capital", checkSize: "$500K–$5M", stage: "Pre-seed–Series A", sectors: "Space economy", techAreas: "GPS/PNT, geospatial, comms, infrastructure", checkType: "Priced equity", traction: "Space-based data/infrastructure thesis fit", url: "https://spacecapital.com", notes: "Publishes the quarterly Space IQ market reports" },
  { name: "SpaceFund", checkSize: "$100K–$2M", stage: "Pre-seed–Series A", sectors: "Space", techAreas: "Launch, stations, logistics, ISRU", checkType: "Priced or SAFE", traction: "Revenue path in the space economy", url: "https://spacefund.com", notes: "Publishes launch/station 'reality ratings' research" },
  { name: "Spaced Ventures", checkSize: "$50K–$1M (syndicate)", stage: "Pre-seed–Seed", sectors: "Space", techAreas: "Launch, satellites, components", checkType: "Crowd SPV", traction: "Community-compelling story + credible tech", url: "https://spacedventures.com", notes: "Retail space-investing platform" },
  { name: "RTX Ventures", checkSize: "$2M–$15M", stage: "Series A–C", sectors: "Aerospace & Defense", techAreas: "Autonomy, propulsion, sensing, space", checkType: "Strategic equity", traction: "Tech relevant to RTX business units", url: "https://www.rtx.com/who-we-are/ventures", notes: "Corporate VC of RTX (Raytheon) — brings prime-contractor channels" },
  { name: "AE Industrial (HorizonX)", checkSize: "$2M–$20M", stage: "Series A–Growth", sectors: "Aerospace, Defense, Industrial", techAreas: "Space, autonomy, digital enterprise", checkType: "Strategic equity", traction: "Scalable tech with aerospace anchor customers", url: "https://ae.industrial.com", notes: "Boeing HorizonX became AEI HorizonX under AE Industrial Partners" },
  { name: "Lockheed Martin Ventures", checkSize: "$1M–$10M", stage: "Seed–Series B", sectors: "Defense, Space", techAreas: "AI, autonomy, space, quantum, energy", checkType: "Strategic equity", traction: "Alignment with LM mission areas; co-development potential", url: "https://lockheedmartin.com/ventures", notes: "Often pairs investment with business-unit sponsorship" },
  { name: "AFVentures / AFWERX", checkSize: "$50K–$15M (STRATFI/TACFI)", stage: "SBIR-stage companies", sectors: "Air & Space", techAreas: "All USAF/USSF mission areas", checkType: "Non-dilutive SBIR + matching", traction: "Phase II SBIR + private/gov match", url: "https://afwerx.com", notes: "Not equity — the Air Force's commercial investment arm; STRATFI matches private dollars" },
  { name: "Harpoon Ventures", checkSize: "$100K–$5M", stage: "Pre-seed–Series A", sectors: "Defense, Deep tech, Energy", techAreas: "Cyber, AI, space, infrastructure", checkType: "Priced equity", traction: "Early gov pull; veteran/operator founders resonate", url: "https://harpoon.vc", notes: "Veteran-led; hands-on with first gov contracts (per VC Sheet: $100K–$5M)" },
  { name: "Humba Ventures", checkSize: "~$750K", stage: "Pre-seed–Seed", sectors: "Deep tech, Defense", techAreas: "Robotics, AI, biotech, manufacturing", checkType: "SAFE or priced", traction: "Technical founders pre-traction; defense-curious deep tech", url: "https://humbaventures.com", notes: "Leo Polovets (ex-Susa) — active, writing-heavy defense-tech thesis" },
  { name: "Fifty Years", checkSize: "$250K–$2M", stage: "Pre-seed–Seed", sectors: "Deep tech, Bio, Climate", techAreas: "Biotech, materials, compute", checkType: "SAFE or priced", traction: "World-positive deep tech; strong science", url: "https://fiftyyears.com", notes: "Deep-tech generalist with dual-use crossover" },
  { name: "Spacecadet Ventures", checkSize: "$100K–$500K", stage: "Pre-seed–Seed", sectors: "Space, AI, Robotics", techAreas: "Space, AI, robotics, biotech", checkType: "SAFE", traction: "Early believers; brand-builders for frontier companies", url: "https://spacecadet.ventures", notes: "" },
  { name: "Julian Capital", checkSize: "$400K–$2M", stage: "Pre-seed–Seed", sectors: "Deep tech", techAreas: "Robotics, biotech, infrastructure", checkType: "SAFE or priced", traction: "Technical differentiation over traction", url: "https://julian.capital", notes: "" },
  { name: "BoxGroup", checkSize: "$250K–$1M", stage: "Pre-seed–Series A", sectors: "Generalist incl. Deep tech", techAreas: "Fintech, deep tech, devtools", checkType: "SAFE or priced", traction: "Founder quality; earliest stage", url: "https://boxgroup.com", notes: "Prolific NYC pre-seed firm" },
  { name: "Marque Ventures", checkSize: "$500K–$3M", stage: "Pre-seed–Series A", sectors: "National security", techAreas: "Autonomy, space, AI, advanced computing", checkType: "Priced equity", traction: "Dual-use with defensible tech", url: "https://marque.vc", notes: "Founded by former SecArmy Ryan McCarthy (venture arm of Section 32 lineage varies — verify)" },
  { name: "Mucker Capital", checkSize: "$100K–$1.5M", stage: "Pre-seed–Seed", sectors: "Software, Dual-use", techAreas: "SaaS, data, applied AI", checkType: "SAFE or priced", traction: "Pre-traction OK with strong team", url: "https://mucker.com", notes: "Hands-on accelerator-style early fund (MuckerLab)" },
  { name: "Backstage Capital", checkSize: "$25K–$100K", stage: "Pre-seed", sectors: "Broad", techAreas: "Software, hardware", checkType: "SAFE", traction: "Underestimated founders; earliest stage", url: "https://backstagecapital.com", notes: "Focused on underrepresented founders" },
  { name: "SU Ventures (Singularity)", checkSize: "$100K–$1M", stage: "Pre-seed–Seed", sectors: "Exponential tech", techAreas: "Space, AI, energy, bio", checkType: "SAFE", traction: "Impact-scale technology", url: "https://su.org", notes: "Programs + early capital" },
  { name: "Boost VC", checkSize: "$500K", stage: "Pre-seed", sectors: "Deep tech, Space", techAreas: "Space, robotics, energy, crypto", checkType: "SAFE (accelerator)", traction: "Sci-fi-grade ambition; pre-product OK", url: "https://boost.vc", notes: "Accelerator + fund; 'we fund sci-fi'" },
  { name: "gener8tor", checkSize: "$100K", stage: "Pre-seed–Seed", sectors: "Broad incl. Dual-use", techAreas: "Varies by program", checkType: "Accelerator investment", traction: "Program-fit; national cohorts incl. gBETA", url: "https://gener8tor.com", notes: "Runs DoD-partnered programs (e.g., with USAF)" },
  { name: "Alchemist Accelerator", checkSize: "$25K–$36K", stage: "Pre-seed", sectors: "Enterprise, Deep tech", techAreas: "B2B, sensors, AI", checkType: "Accelerator SAFE", traction: "Enterprise sales motion", url: "https://alchemistaccelerator.com", notes: "Enterprise-only accelerator; AlchemistX gov programs" },
  { name: "Decisive Point", checkSize: "$500K–$4M", stage: "Seed–Series A", sectors: "Defense, Energy, Space", techAreas: "Autonomy, energy, advanced manufacturing", checkType: "Priced equity", traction: "SBIR/gov R&D transition stories", url: "https://decisivepoint.com", notes: "Specializes in helping SBIR companies cross the valley of death" },
  { name: "Village Global", checkSize: "$250K–$1.5M", stage: "Pre-seed–Seed", sectors: "Broad", techAreas: "AI, infrastructure", checkType: "SAFE", traction: "Network-driven; strong founders", url: "https://villageglobal.vc", notes: "Backed by tech luminaries" },
  { name: "Countdown Capital (wound down — see notes)", checkSize: "—", stage: "—", sectors: "Space, Industrial", techAreas: "Hard tech", checkType: "—", traction: "—", url: "https://countdown.capital", notes: "Notable early space fund that returned capital in 2024; listed for landscape awareness" },
  { name: "Seraphim Space", checkSize: "$250K–$5M", stage: "Pre-seed–Series B", sectors: "Space", techAreas: "EO, comms, in-orbit services", checkType: "Priced equity", traction: "Space-tech thesis; accelerator available", url: "https://seraphim.vc", notes: "Space-dedicated fund + Space Camp accelerator" },
  { name: "Razor's Edge Ventures", checkSize: "$2M–$15M", stage: "Series A–B", sectors: "National security", techAreas: "Space, cyber, AI/ML, signal processing", checkType: "Priced equity", traction: "Mission-validated tech; cleared teams a plus", url: "https://razorsedgevc.com", notes: "Deep IC/DoD operating roots" },
  { name: "Scout Ventures", checkSize: "$500K–$3M", stage: "Pre-seed–Series A", sectors: "Frontier & Dual-use", techAreas: "AI, robotics, space, quantum", checkType: "Priced equity", traction: "Veteran/intel founders; dual-use", url: "https://scoutventures.com", notes: "Veteran-founded" },
  { name: "Refinery Ventures", checkSize: "$500K–$2M", stage: "Seed", sectors: "Dual-use, Enterprise", techAreas: "AI, logistics, security", checkType: "Priced equity", traction: "Early enterprise/gov revenue", url: "https://refinery.vc", notes: "Mid-America dual-use focus" },
  { name: "Stellar Ventures", checkSize: "$250K–$2M", stage: "Pre-seed–Seed", sectors: "Space", techAreas: "Space infrastructure, defense", checkType: "Priced or SAFE", traction: "Space economy fit", url: "https://stellar.vc", notes: "Space-focused early fund" },
  { name: "Type One Ventures", checkSize: "$100K–$2M", stage: "Pre-seed–Seed", sectors: "Space, Deep tech", techAreas: "Manufacturing, robotics, space", checkType: "Priced or SAFE", traction: "Frontier-tech founders", url: "https://typeone.ventures", notes: "" },
  { name: "Cantos Ventures", checkSize: "$400K–$1.5M", stage: "Pre-seed", sectors: "Deep tech", techAreas: "Space, energy, bio, compute", checkType: "SAFE", traction: "'Neo-industrial' pre-product bets", url: "https://cantos.vc", notes: "" },
  { name: "Also Capital / angels via OpenVC", checkSize: "$10K–$250K", stage: "Angel", sectors: "Defense tech", techAreas: "Varies", checkType: "SAFE", traction: "Use the OpenVC defense list to filter angels by thesis", url: "https://www.openvc.app/investor-lists/defensetech-investors", notes: "Community-maintained list — filter by check size and stage" },
];

const RAW_ACCELERATORS = [
  { name: "Catalyst Accelerator", focus: "Space & defense (USSF-aligned)", location: "Colorado Springs, CO", terms: "Non-dilutive; cohort-based", cohort: "~8 companies / 2x yr", url: "https://www.catalystaccelerator.space", tips: "Topics track Space Force mission gaps; strong on-ramp to SDA/SSC customers" },
  { name: "Hyperspace Challenge", focus: "Space startups + universities (AFRL)", location: "Albuquerque, NM", terms: "Non-dilutive; prize + gov matchmaking", cohort: "Annual", url: "https://hyperspacechallenge.com", tips: "Built around direct collaboration with AFRL/Space RCO problem owners" },
  { name: "Techstars Space (TVX/Boulder lineage)", focus: "Aerospace & defense", location: "Los Angeles / various", terms: "$120K for 6% (standard Techstars)", cohort: "~12 / yr", url: "https://www.techstars.com", tips: "Alumni network + Allied Space partners; apply with clear dual-use story" },
  { name: "Y Combinator", focus: "All (growing defense cohort)", location: "San Francisco, CA", terms: "$500K standard deal", cohort: "2x yr", url: "https://www.ycombinator.com", tips: "Defense-tech is now a named YC category; speed + demo-day distribution" },
  { name: "Starburst Aerospace", focus: "Aviation, space & defense", location: "LA / global", terms: "Varies by program (some equity-free)", cohort: "Rolling", url: "https://starburst.aero", tips: "Strong prime/agency connections (incl. NASA & USSF programs)" },
  { name: "AngelPad", focus: "Software/enterprise", location: "SF / NYC", terms: "$120K for 7%", cohort: "2x yr", url: "https://angelpad.com", tips: "Small cohorts, intense mentorship" },
  { name: "500 Global", focus: "Broad", location: "Global", terms: "$150K for 6% (flagship)", cohort: "Multiple", url: "https://500.co", tips: "Wide network; better for commercial traction than gov" },
  { name: "Alchemist Accelerator", focus: "Enterprise & deep tech", location: "SF Bay Area", terms: "~$25K–36K for ~5%", cohort: "3x yr", url: "https://alchemistaccelerator.com", tips: "AlchemistX runs government innovation programs" },
  { name: "Antler", focus: "Company building (idea stage)", location: "Global", terms: "~$250K post-residency (varies)", cohort: "Rolling", url: "https://antler.co", tips: "Good for pre-team founders" },
  { name: "The Engine (MIT)", focus: "Tough tech", location: "Cambridge, MA", terms: "Equity investment + labs", cohort: "Rolling", url: "https://engine.xyz", tips: "Purpose-built for hard-tech; pair with MIT $100K competition for students" },
  { name: "MIT $100K Competition", focus: "Student ventures", location: "Cambridge, MA", terms: "Non-dilutive prizes", cohort: "Annual", url: "https://www.mit100k.org", tips: "Excellent early validation + press for MIT-affiliated teams" },
  { name: "NSIN (National Security Innovation Network)", focus: "Dual-use ventures + talent", location: "National", terms: "Non-dilutive programs (Propel, Vector...)", cohort: "Multiple/yr", url: "https://www.nsin.mil", tips: "Direct DoD problem-sponsor matchmaking; great first gov step" },
  { name: "Army xTech", focus: "Army modernization areas", location: "National", terms: "Non-dilutive prizes ($10K–$250K+) + SBIR fast-track", cohort: "Multiple competitions", url: "https://xtech.army.mil", tips: "Winning often comes with a direct-to-Phase-II SBIR invitation" },
  { name: "APEX Accelerators (ex-PTAC)", focus: "Gov contracting readiness", location: "Every state", terms: "Free counseling", cohort: "Ongoing", url: "https://www.apexaccelerators.us", tips: "Not a startup accelerator — free one-on-one contracting help; use it alongside everything else" },
  { name: "SBDC / TechConnect programs", focus: "Small business + SBIR support", location: "State networks", terms: "Free/low-cost", cohort: "Ongoing", url: "https://americassbdc.org", tips: "State SBDCs + TechConnect events surface SBIR partners and primes" },
  { name: "Plug and Play (Aerospace & Defense)", focus: "Corporate-connected innovation", location: "Sunnyvale + global", terms: "Often equity-free programs", cohort: "2x yr", url: "https://www.plugandplaytechcenter.com", tips: "Corporate partners incl. primes; good for pilots" },
  { name: "DARPA programs (EMBER/Bridges etc.)", focus: "Frontier R&D transition", location: "National", terms: "Contract funding (non-dilutive)", cohort: "Program-dependent", url: "https://www.darpa.mil/work-with-us", tips: "Not an accelerator per se — watch BAAs and Disruption Opportunities for startup-friendly entries" },
  { name: "AeroInnovate (UW Oshkosh)", focus: "Aviation/aerospace", location: "Virtual + WI", terms: "Program fee/equity varies", cohort: "Annual", url: "https://aeroinnovate.org", tips: "Aviation-specific mentorship + EAA AirVenture exposure" },
  { name: "a16z speedrun", focus: "Games/AI/frontier (incl. defense-adjacent)", location: "LA", terms: "Up to $1M for ~7% (varies)", cohort: "2x yr", url: "https://a16z.com/games/speedrun/", tips: "Large checks for an accelerator; competitive" },
  { name: "Capital Factory (Center for Defense Innovation)", focus: "Texas startups + defense", location: "Austin/Dallas, TX", terms: "Membership/equity options", cohort: "Rolling", url: "https://capitalfactory.com", tips: "Hosts Army/AFWERX/DIU touchpoints; strong Texas defense network" },
  { name: "AI2 Incubator", focus: "Applied AI", location: "Seattle, WA", terms: "Equity investment + technical support", cohort: "Rolling", url: "https://www.ai2incubator.com", tips: "Deep AI bench from the Allen Institute" },
  { name: "IARPA (engagement, not accelerator)", focus: "Intelligence community R&D", location: "National", terms: "Contract research", cohort: "BAA-driven", url: "https://www.iarpa.gov", tips: "For frontier IC-relevant research; watch for proposers' days" },
  { name: "Army Applications Laboratory (AAL)", focus: "Army problem-driven cohorts", location: "Austin, TX", terms: "Non-dilutive contracts (SPARTN)", cohort: "Program-based", url: "https://aal.army", tips: "Cohorts formed around specific Army problems with paid pilots" },
  { name: "NavalX / Tech Bridges", focus: "Navy & Marine Corps innovation", location: "17+ regional Tech Bridges", terms: "Non-dilutive; agreements vary", cohort: "Ongoing", url: "https://www.secnav.navy.mil/agility/Pages/navalx.aspx", tips: "Regional front doors to Navy labs and program offices" },
  { name: "NATO DIANA", focus: "Allied dual-use deep tech", location: "Accelerator sites across NATO", terms: "€100K+ non-dilutive grants", cohort: "Annual challenges", url: "https://www.diana.nato.int", tips: "Opens allied markets; challenge topics published annually" },
  { name: "IQT Emerge", focus: "Deep-tech for national security", location: "US", terms: "Program + potential IQT investment", cohort: "Cohort-based", url: "https://www.iqt.org", tips: "Bridges commercial startups to IC needs" },
  { name: "Boost VC", focus: "Sci-fi tech (space, robotics)", location: "San Mateo, CA", terms: "$500K for 15% (verify current)", cohort: "2x yr", url: "https://boost.vc", tips: "Also listed under investors; earliest-stage friendly" },
  { name: "Seraphim Space Camp", focus: "Space tech", location: "UK/global (remote-friendly)", terms: "Investment-linked", cohort: "2x yr", url: "https://seraphim.vc", tips: "Backed by the space-dedicated Seraphim fund" },
  { name: "Mach33 / other space studios", focus: "Space venture studios", location: "Various", terms: "Studio equity models", cohort: "Rolling", url: "https://mach33.aero", tips: "Studio model = heavier equity but heavier help; compare terms carefully" },
  { name: "gBETA / gener8tor programs", focus: "Regional + DoD-partnered", location: "National", terms: "Equity-free (gBETA) or investment (gener8tor)", cohort: "Multiple", url: "https://gener8tor.com", tips: "gBETA is free/no-equity — a gentle first accelerator" },
];

/* ── Enrichment maps (merged below) ─────────────────────────────────────
   Program logistics move every cycle — these are honest, verify-on-site
   values; "check site" means the program publishes dates per cohort. */
const ACCEL_META = {
  "Catalyst Accelerator": { dueDate: "Per-cohort (check site)", durationWeeks: 12, attendance: "Onsite (CO Springs)", phase: "Seed–Series A" },
  "Hyperspace Challenge": { dueDate: "Annual (fall)", durationWeeks: 10, attendance: "Hybrid", phase: "Any" },
  "Techstars Space (TVX/Boulder lineage)": { dueDate: "2x yr (check site)", durationWeeks: 13, attendance: "Onsite (LA)", phase: "Pre-seed–Seed" },
  "Y Combinator": { dueDate: "2x yr (Apr/Oct)", durationWeeks: 12, attendance: "Onsite (SF)", phase: "Idea–Seed" },
  "Starburst Aerospace": { dueDate: "Rolling", durationWeeks: 13, attendance: "Hybrid", phase: "Pre-seed–Series A" },
  "AngelPad": { dueDate: "2x yr", durationWeeks: 12, attendance: "Onsite (SF/NYC)", phase: "Pre-seed–Seed" },
  "500 Global": { dueDate: "Multiple cohorts", durationWeeks: 16, attendance: "Hybrid", phase: "Seed" },
  "Alchemist Accelerator": { dueDate: "3x yr", durationWeeks: 24, attendance: "Hybrid", phase: "Pre-seed–Seed" },
  "Antler": { dueDate: "Rolling", durationWeeks: 26, attendance: "Onsite (global sites)", phase: "Idea" },
  "The Engine (MIT)": { dueDate: "Rolling", durationWeeks: null, attendance: "Onsite (Cambridge)", phase: "Pre-seed–Series A" },
  "MIT $100K Competition": { dueDate: "Annual (spring finals)", durationWeeks: 12, attendance: "Onsite (MIT)", phase: "Idea" },
  "NSIN (National Security Innovation Network)": { dueDate: "Program-dependent", durationWeeks: 8, attendance: "Hybrid", phase: "Any" },
  "Army xTech": { dueDate: "Multiple competitions/yr", durationWeeks: 16, attendance: "Virtual + demo events", phase: "Any" },
  "APEX Accelerators (ex-PTAC)": { dueDate: "Ongoing", durationWeeks: null, attendance: "Virtual/local office", phase: "Any" },
  "SBDC / TechConnect programs": { dueDate: "Ongoing", durationWeeks: null, attendance: "Virtual/local", phase: "Any" },
  "Plug and Play (Aerospace & Defense)": { dueDate: "2x yr", durationWeeks: 12, attendance: "Hybrid", phase: "Seed–Series B" },
  "DARPA programs (EMBER/Bridges etc.)": { dueDate: "BAA-dependent", durationWeeks: null, attendance: "Virtual", phase: "Any" },
  "AeroInnovate (UW Oshkosh)": { dueDate: "Annual", durationWeeks: 10, attendance: "Virtual", phase: "Idea–Seed" },
  "a16z speedrun": { dueDate: "2x yr", durationWeeks: 12, attendance: "Onsite (LA)", phase: "Pre-seed–Seed" },
  "Capital Factory (Center for Defense Innovation)": { dueDate: "Rolling", durationWeeks: null, attendance: "Onsite (TX)", phase: "Any" },
  "AI2 Incubator": { dueDate: "Rolling", durationWeeks: null, attendance: "Onsite (Seattle)", phase: "Idea–Seed" },
  "IARPA (engagement, not accelerator)": { dueDate: "BAA-dependent", durationWeeks: null, attendance: "Virtual", phase: "Any" },
  "Army Applications Laboratory (AAL)": { dueDate: "Per problem set", durationWeeks: 12, attendance: "Hybrid (Austin)", phase: "Any" },
  "NavalX / Tech Bridges": { dueDate: "Ongoing", durationWeeks: null, attendance: "Regional offices", phase: "Any" },
  "NATO DIANA": { dueDate: "Annual challenges (summer)", durationWeeks: 26, attendance: "Hybrid (allied sites)", phase: "Seed" },
  "IQT Emerge": { dueDate: "Per cohort", durationWeeks: 12, attendance: "Hybrid", phase: "Seed–Series A" },
  "Boost VC": { dueDate: "2x yr", durationWeeks: 13, attendance: "Onsite (San Mateo)", phase: "Pre-seed" },
  "Seraphim Space Camp": { dueDate: "2x yr", durationWeeks: 11, attendance: "Hybrid", phase: "Seed–Series A" },
  "Mach33 / other space studios": { dueDate: "Rolling", durationWeeks: null, attendance: "Varies", phase: "Idea" },
  "gBETA / gener8tor programs": { dueDate: "Multiple cohorts", durationWeeks: 7, attendance: "Hybrid (regional)", phase: "Idea–Seed" },
};

const INVESTOR_PORTFOLIO = {
  "Founders Fund": "Anduril, SpaceX, Palantir, Scale AI",
  "Andreessen Horowitz (American Dynamism)": "Anduril, Hadrian, Shield AI, Castelion",
  "Shield Capital": "HawkEye 360, Rebellion Defense, Albedo",
  "Lux Capital": "Anduril, Hadrian, Varda, Saildrone",
  "Khosla Ventures": "Rocket Lab (early), DEUS robotics bets, fusion portfolio",
  "General Catalyst": "Anduril, Helsing, Vannevar Labs",
  "8VC": "Palantir lineage, Saronic, Resilience",
  "In-Q-Tel (IQT)": "Palantir (early), Databricks, Rocket Lab",
  "Space Capital": "Planet, Skydio, Muon Space",
  "SpaceFund": "Axiom Space, Orbit Fab",
  "RTX Ventures": "Hermeus, Ursa Major, EpiSci",
  "Lockheed Martin Ventures": "Terran Orbital, ABL Space, Machina Labs",
  "Harpoon Ventures": "Anduril (early), Shield AI, Corsha",
  "Humba Ventures": "Castelion, Mach Industries",
};

const ACCEL_DEFAULTS = { dueDate: "Check site", durationWeeks: null, attendance: "Varies", phase: "Any" };

export const ACCELERATORS = RAW_ACCELERATORS.map((r) => ({ ...ACCEL_DEFAULTS, ...(ACCEL_META[r.name] || {}), ...r }));
export const INVESTORS = RAW_INVESTORS.map((r) => ({ portfolio: INVESTOR_PORTFOLIO[r.name] || "", ...r }));
